theme: minima
title: M Plus H
author: M Plus H
email: contactmplush@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Looking to build a nexus between data, civics and marketing.

# social links
instagram_username: mplushmplush # DO NOT include the @ character, or else the build will fail!
github_username:  mplushmplush  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
